on: push
name: Deploy to Heroku
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `master` branch
        uses: actions/checkout@master
      - name: Add Heroku remote
        uses: actions/heroku@1.0.0
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: git:remote -a gh-action-test-flask
      - name: Push to Heroku
        run: git push heroku master
