on: push
name: Deploy to Heroku
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `master` branch
        uses: actions/checkout@master
      - name: Add Heroku remote
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: git:remote -a gh-action-test-flask
      - name: Push to Heroku
        run: |
          git fetch --all --unshallow
          echo "machine git.heroku.com\n  login ${{ secrets.HEROKU_EMAIL }}\n  password ${{ secrets.HEROKU_API_KEY }}" > $HOME/.netrc
          cat $HOME/.netrc
          git push heroku master
