on: push

name: Deploy to Heroku
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `master` branch
        uses: actions/checkout@master
      - name: Add credentials to netrc
        run: |
          echo "machine git.heroku.com" >>  $HOME/.netrc
          echo "  login ${{ secrets.HEROKU_EMAIL }}" >> $HOME/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> $HOME/.netrc
      - name: Add Heroku remote
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: git:remote -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to heroku
        run: |
          git fetch origin --unshallow
          git push heroku master
